<a href="https://colab.research.google.com/github/pavanteja41/pavanteja41/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
print(np.version,np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'> <function show at 0x7f08e6011c20>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ls=[1,2,3,4]
num=np.array(ls)
print(num.size*num.itemsize)

32


In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
num=np.zeros(10)
num[4]=1

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
v=np.arange(10,49)

In [ ]:
v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [ ]:
mat=np.arange(0,9).reshape(3,3)

In [ ]:
given_array=[1,2,0,0,4,0]
np.nonzero(given_array)

(array([0, 1, 4]),)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((3,3,3))

array([[[0.32862301, 0.68562333, 0.57898669],
        [0.40993266, 0.40255704, 0.95075276],
        [0.30823842, 0.46795218, 0.6422246 ]],

       [[0.50167361, 0.9624808 , 0.05635718],
        [0.06737799, 0.23979527, 0.36679671],
        [0.8722733 , 0.94918909, 0.60550234]],

       [[0.24561661, 0.17414731, 0.33815024],
        [0.1271672 , 0.42543256, 0.26148113],
        [0.68619255, 0.08607292, 0.36408076]]])

In [ ]:
x=np.random.random((10,10))
print(x)
print(x.min(),x.max())

[[0.45072718 0.77885861 0.03112811 0.19066478 0.00737625 0.31670121
  0.28675891 0.3547956  0.19201212 0.37539047]
 [0.52179954 0.91099258 0.82123321 0.28324566 0.15355499 0.22828525
  0.49025663 0.62126212 0.3750017  0.26901205]
 [0.15636722 0.17163009 0.52806226 0.99120988 0.90036342 0.04434636
  0.22304735 0.40828094 0.02520007 0.58600761]
 [0.85809232 0.70085748 0.65837202 0.37698935 0.00968262 0.46034843
  0.61468252 0.41059049 0.19589836 0.93552334]
 [0.24916827 0.66767521 0.06402965 0.07591495 0.01240214 0.68073158
  0.75033905 0.12394985 0.17172693 0.98541398]
 [0.289483   0.20986948 0.57105325 0.37401542 0.33935436 0.44070334
  0.20186445 0.1570095  0.59434307 0.30726848]
 [0.49997496 0.08419178 0.61425493 0.10763262 0.84515839 0.6193067
  0.83477682 0.58099903 0.24121829 0.30807396]
 [0.32943238 0.17609569 0.08044209 0.20154189 0.98301989 0.98951874
  0.53234835 0.36625004 0.05820735 0.69021063]
 [0.2716578  0.39680313 0.72838422 0.7672284  0.52186721 0.26591136
  0.73158145 

In [ ]:
x=np.random.random(30)
x.mean()

0.42206603780311125

In [ ]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x
np.pad(x,1,'constant',constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
arr = np.array([[0,1],
               [1,0]])
arr = np.tile(arr,(4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
np.random.random((5,5))
xmin,xmax=x.min(),x.max()
x=(x-xmin)/(xmax-xmin)
x

array([[0.82712591, 0.92846117, 0.89362598, 0.54480057, 0.97770125],
       [0.82503693, 0.44720232, 0.00973781, 0.18123154, 0.98733005],
       [1.        , 0.97937937, 0.74113671, 0.41546781, 0.9234842 ],
       [0.33626571, 0.06031344, 0.06496532, 0.        , 0.83207266],
       [0.47401504, 0.48725966, 0.47785349, 0.25918796, 0.59983541]])

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

In [ ]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[1.76475595 0.90312668]
 [0.90650096 0.56914959]
 [1.90445406 1.08773022]
 [1.13154497 0.70815922]
 [1.25300183 0.7082832 ]]


array([[1.76475595, 0.90312668],
       [0.90650096, 0.56914959],
       [1.90445406, 1.08773022],
       [1.13154497, 0.70815922],
       [1.25300183, 0.7082832 ]])

In [ ]:
arr = np.arange(16)
print(arr>=3)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [4]:
Z = np.arange(10)
# Z**Z
# Z_2 = 2 << Z >> 2
#Z_2
#print([bin(2) for z in Z_2])
#print([bin(z) for z in 2 << Z_2])
#print([bin(z) for z in Z_2])
#Z<Z>Z

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [ ]:
arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr)

[[0.14792949 0.52228764 0.14749388 0.9696379  0.89855783]
 [0.3980568  0.09729235 0.42489758 0.84662634 0.96666728]
 [0.21186812 0.79113012 0.77122236 0.65459337 0.10370223]
 [0.29169366 0.97560008 0.12977823 0.38620735 0.03291223]
 [0.37889038 0.88687427 0.13521151 0.48084483 0.41246839]]
[[0.15 0.52 0.15 0.97 0.9 ]
 [0.4  0.1  0.42 0.85 0.97]
 [0.21 0.79 0.77 0.65 0.1 ]
 [0.29 0.98 0.13 0.39 0.03]
 [0.38 0.89 0.14 0.48 0.41]]


In [ ]:
x=np.array([0,1,2,32,4,5,6,7,8,99])
y=np.array([1,2,3,5,6,7])
print(np.intersect1d(x,y))

[1 2 5 6 7]


In [8]:
# # Suicide mode on
# defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# # Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
     Z = np.ones(1) / 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


NameError: ignored

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [10]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [11]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [13]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

In [16]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(np.trunc(Z))

[2. 9. 5. 3. 4. 7. 2. 4. 5. 4.]
[2. 9. 5. 3. 4. 7. 2. 4. 5. 4.]
[2. 9. 5. 3. 4. 7. 2. 4. 5. 4.]
[2 9 5 3 4 7 2 4 5 4]
[2. 9. 5. 3. 4. 7. 2. 4. 5. 4.]


In [17]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [20]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.18133109 0.1949648  0.21268197 0.23940252 0.24502034 0.25392773
 0.31867174 0.46954589 0.74480622 0.95589977]


In [21]:
import functools as ft
Z = np.arange(10)
#np.add.reduce(Z)
ft.reduce(np.add,Z,0)

45

In [22]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print('*'*60)
print(B)
print('*'*60)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 1 1 0]
************************************************************
[0 0 0 1 0]
************************************************************
False
False


In [24]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1

In [25]:
import numpy as np
z= np.random.randint(0,9,(10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[1.41421356 0.78539816]
 [4.12310563 1.32581766]
 [1.         0.        ]
 [6.40312424 0.67474094]
 [3.         0.        ]
 [7.61577311 1.16590454]
 [5.83095189 0.5404195 ]
 [3.60555128 0.5880026 ]
 [7.21110255 0.98279372]
 [5.65685425 0.78539816]]


In [26]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[0.5400838  0.82985153 0.51443513 0.53629943 0.65241873 0.27737411
 0.50389297 0.64710725 0.81153554 0.88209882]
[0.5400838  0.82985153 0.51443513 0.53629943 0.65241873 0.27737411
 0.50389297 0.64710725 0.81153554 0.        ]


In [27]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [28]:
# X = np.random.randint(0,11,(5,5))
# Y = np.random.randint(11,22,(5,5))
# C = 1/(Y-X.T)
# C

Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
#print(X)
X  = np.tile(X,(10,1)).T
#print(X)

C = 1/(X - Y)
C

array([[0.1       , 0.16666667, 0.07692308, 0.125     , 0.09090909,
        0.16666667, 0.08333333, 0.16666667, 0.14285714, 0.11111111],
       [0.07692308, 0.11111111, 0.0625    , 0.09090909, 0.07142857,
        0.11111111, 0.06666667, 0.11111111, 0.1       , 0.08333333],
       [0.08333333, 0.125     , 0.06666667, 0.1       , 0.07692308,
        0.125     , 0.07142857, 0.125     , 0.11111111, 0.09090909],
       [0.08333333, 0.125     , 0.06666667, 0.1       , 0.07692308,
        0.125     , 0.07142857, 0.125     , 0.11111111, 0.09090909],
       [0.1       , 0.16666667, 0.07692308, 0.125     , 0.09090909,
        0.16666667, 0.08333333, 0.16666667, 0.14285714, 0.11111111],
       [0.09090909, 0.14285714, 0.07142857, 0.11111111, 0.08333333,
        0.14285714, 0.07692308, 0.14285714, 0.125     , 0.1       ],
       [0.14285714, 0.33333333, 0.1       , 0.2       , 0.125     ,
        0.33333333, 0.11111111, 0.33333333, 0.25      , 0.16666667],
       [0.07692308, 0.11111111, 0.0625   

In [29]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [30]:
z=[]
print(z)

[]


In [31]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[4.04618744 0.18618329 3.54419808 7.3657313  4.96852511 1.65197639
 7.4098635  4.00852322 1.29698258 3.74956284]
************************************************************
4.968525107137587


In [32]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [33]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.56936637 0.723202   0.65873946 0.90923165 0.55125171
  0.30082529 0.97386892 0.92654918 0.55759127]
 [0.56936637 0.         0.15396008 0.14865474 0.47199145 0.58991878
  0.52570749 0.43613634 0.54493608 0.16250127]
 [0.723202   0.15396008 0.         0.15458386 0.42015944 0.69143298
  0.65879574 0.31564657 0.49951723 0.25108244]
 [0.65873946 0.14865474 0.15458386 0.         0.32333774 0.54260551
  0.66138241 0.31577339 0.64422011 0.11619057]
 [0.90923165 0.47199145 0.42015944 0.32333774 0.         0.57622385
  0.9700786  0.23419588 0.90727754 0.37197615]
 [0.55125171 0.58991878 0.69143298 0.54260551 0.57622385 0.
  0.77858297 0.75868367 1.12986425 0.44188341]
 [0.30082529 0.52570749 0.65879574 0.66138241 0.9700786  0.77858297
  0.         0.9616194  0.69491726 0.59910597]
 [0.97386892 0.43613634 0.31564657 0.31577339 0.23419588 0.75868367
  0.9616194  0.         0.73603442 0.41938925]
 [0.92654918 0.54493608 0.49951723 0.64422011 0.90727754 1.12986425
  0.69491726 0.73603

In [34]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [35]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


In [36]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [37]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [39]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)
np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
#print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [42]:
Z = np.random.randint(0,10,(5,5))
print(Z)


# Z_1 = Z
# for ind in range(5):
#     Z_1[:,ind].sort()
#print(Z_1)


print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[9 6 4 3 8]
 [6 9 8 4 2]
 [9 7 4 0 5]
 [9 4 1 0 3]
 [9 4 3 9 5]]
[[6 9 8 4 2]
 [9 7 4 0 5]
 [9 6 4 3 8]
 [9 4 1 0 3]
 [9 4 3 9 5]]
[[8 3 9 4 6]
 [2 4 6 8 9]
 [5 0 9 4 7]
 [3 0 9 1 4]
 [5 9 9 3 4]]


In [43]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[False False  True False False  True False False False False]
 [ True False  True False  True  True  True  True  True False]
 [False False  True  True False  True False  True  True False]]
[[ True  True False  True  True False  True  True  True  True]
 [False  True False  True False False False False False  True]
 [ True  True False False  True False  True False False  True]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False])

In [44]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.47092911651371594


In [45]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [46]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [47]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 2. 5. 1. 3. 3. 2. 4. 4. 3.]
[5. 3. 9. 1. 5. 5. 3. 7. 7. 5.]


In [48]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [49]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


In [50]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[40 63 75 63]
 [53 39 34 54]
 [58 66 48 55]]
[[40 63 75 63]
 [53 39 34 54]
 [58 66 48 55]]


In [51]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.61412978 0.60644333 0.59511024 0.59469214 0.50897436 0.54204076
 0.41136443 0.59247452 0.37562647 0.47834853]
0    0.614130
1    0.606443
2    0.595110
3    0.594692
4    0.508974
5    0.542041
6    0.411364
7    0.592475
8    0.375626
9    0.478349
dtype: float64


In [52]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.74967486, 1.23844184, 1.34115147, 1.119361  , 0.99381318])

In [53]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [54]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [55]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 30) ( 0, 33) ( 9, 11) ( 9, 19) (11, 19) (11, 56) (11, 58) (16, 72)
 (16, 76) (29, 46) (29, 83) (30, 33) (31, 32) (31, 65) (32, 65) (33, 61)
 (33, 99) (35, 55) (35, 95) (44, 53) (44, 71) (46, 83) (53, 71) (55, 95)
 (56, 58) (57, 61) (57, 85) (61, 85) (61, 99) (72, 76)]


In [57]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [3]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [4]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [5]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.11725856,  0.72963091, -0.4175074 , -0.3736513 , -0.01784048,
        0.25441341,  0.95094955, -0.93542278,  0.54071548,  0.54476531,
        0.11833325, -0.16211164, -0.55008951,  0.62798761, -0.48678026,
        0.19809701,  0.77182101,  0.95628489, -0.1073574 , -0.14784183,
       -0.9203047 , -0.63241671,  0.17000701, -0.99944332, -0.1170025 ,
       -0.35015318,  0.73833127, -0.09821838,  0.75233486,  0.24490779,
       -0.71605242, -0.3726384 , -0.96597754,  0.66726002, -0.85504253,
        0.43641934, -0.14057841,  0.74238101, -0.97816875,  0.9091496 ,
       -0.07407654,  0.1123939 , -0.78155337,  0.37540815, -0.10853958,
       -0.17113579,  0.19777028,  0.07444114, -0.42368417,  0.17494383,
       -0.69061001,  0.42216325,  0.56887935, -0.0477086 ,  0.11266823,
       -0.28194829,  0.23621302,  0.86617314,  0.69663986,  0.8190167 ,
       -0.60959344, -0.48959474, -0.04956268,  0.72385794,  0.52872532,
       -0.36140827, -0.37787089,  0.82179205,  0.87563123,  0.91

In [6]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.80490926 12.441081    3.87121867  5.60771847  1.19045356  4.1189179
  3.03918846  6.19368445  7.41596107 13.56373547]


In [7]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.03387546e+01 1.88666324e+01 1.30166882e+01 1.60741899e+01
  1.16068177e+01 5.40799819e+00 6.14055511e+00 1.95294112e-01
  9.03544228e-01 2.00612342e+00]
 [8.49419484e+00 2.13796180e-01 2.22266905e+00 3.38928655e-02
  4.98864430e+00 9.24518991e+00 1.60090525e+00 9.20102962e+00
  1.07341960e+01 1.20561015e+01]
 [8.83330145e+00 1.31460787e+00 9.76907607e+00 6.63796757e+00
  1.09588800e+01 4.10524618e+00 1.37160415e+01 2.79367775e+00
  1.08852801e+00 2.63857077e+00]
 [3.77695051e-01 8.40511018e+00 1.32364550e+00 4.40159642e+00
  3.92505133e-03 7.33895784e-01 3.93645300e+00 1.30183538e+00
  1.08732977e-01 6.00654347e-01]
 [2.63689938e+00 1.06701708e+01 3.31922687e+00 6.47278688e+00
  2.11747538e+00 5.82620198e-01 2.73199974e+00 2.14890112e+00
  7.94215306e-01 8.63548181e-01]
 [5.83219695e+00 1.81059303e+00 6.40887501e+00 3.26403557e+00
  7.58765901e+00 2.99729684e+00 1.09479782e+01 2.73247974e+00
  1.11757578e+00 1.63679453e+00]
 [8.39676241e+00 1.51519759e-01 4.95994454e+00 2.35498208e

In [8]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 2 4 0 6 4 4 4 0 5]
 [5 8 7 4 0 7 5 6 0 0]
 [0 5 2 6 6 4 0 7 3 9]
 [8 6 3 5 5 5 2 9 6 0]
 [9 6 5 3 8 1 9 5 3 1]
 [9 9 5 2 6 4 3 7 5 6]
 [0 6 9 2 3 6 9 8 0 7]
 [8 2 8 5 3 8 4 7 9 4]
 [3 4 5 0 1 7 9 2 1 6]
 [6 1 1 9 3 3 6 5 3 7]]
[[0 0 0 0 0]
 [0 2 2 4 0]
 [0 5 8 7 4]
 [0 0 5 2 6]
 [0 8 6 3 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [9]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [10]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [11]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


In [12]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[2 0 3]
   [3 2 3]
   [1 2 0]]

  [[0 3 4]
   [2 3 1]
   [2 0 2]]

  [[3 4 3]
   [3 1 3]
   [0 2 3]]

  [[4 3 1]
   [1 3 4]
   [2 3 4]]

  [[3 1 1]
   [3 4 0]
   [3 4 0]]

  [[1 1 0]
   [4 0 4]
   [4 0 0]]

  [[1 0 3]
   [0 4 0]
   [0 0 1]]

  [[0 3 3]
   [4 0 2]
   [0 1 4]]]


 [[[3 2 3]
   [1 2 0]
   [2 0 2]]

  [[2 3 1]
   [2 0 2]
   [0 2 3]]

  [[3 1 3]
   [0 2 3]
   [2 3 1]]

  [[1 3 4]
   [2 3 4]
   [3 1 3]]

  [[3 4 0]
   [3 4 0]
   [1 3 1]]

  [[4 0 4]
   [4 0 0]
   [3 1 3]]

  [[0 4 0]
   [0 0 1]
   [1 3 3]]

  [[4 0 2]
   [0 1 4]
   [3 3 0]]]


 [[[1 2 0]
   [2 0 2]
   [3 0 3]]

  [[2 0 2]
   [0 2 3]
   [0 3 3]]

  [[0 2 3]
   [2 3 1]
   [3 3 2]]

  [[2 3 4]
   [3 1 3]
   [3 2 1]]

  [[3 4 0]
   [1 3 1]
   [2 1 4]]

  [[4 0 0]
   [3 1 3]
   [1 4 2]]

  [[0 0 1]
   [1 3 3]
   [4 2 0]]

  [[0 1 4]
   [3 3 0]
   [2 0 4]]]


 [[[2 0 2]
   [3 0 3]
   [2 0 1]]

  [[0 2 3]
   [0 3 3]
   [0 1 4]]

  [[2 3 1]
   [3 3 2]
   [1 4 4]]

  [[3 1 3]
   [3 2 1]
   [4 4 2]]

  [[1 3 1]
   

In [13]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 12 10  3  8]
 [12  3 10  6 10]
 [10 10  6 42 10]
 [ 3  6 42  8 16]
 [ 8 10 10 16  9]]


In [14]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [15]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [16]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9998 9996 9995]


In [18]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [19]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [20]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.94 s ± 210 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
162 ms ± 7.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
139 ms ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 5 6]


In [22]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 3]
 [0 2 2]
 [3 3 2]
 [2 1 4]
 [1 1 4]
 [4 0 0]
 [4 3 3]
 [1 0 2]
 [0 3 4]
 [4 3 4]]
[[4 1 3]
 [0 2 2]
 [3 3 2]
 [2 1 4]
 [1 1 4]
 [4 0 0]
 [4 3 3]
 [1 0 2]
 [0 3 4]
 [4 3 4]]
[[4 1 3]
 [0 2 2]
 [3 3 2]
 [2 1 4]
 [1 1 4]
 [4 0 0]
 [4 3 3]
 [1 0 2]
 [0 3 4]
 [4 3 4]]


In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [24]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


In [25]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[2.36994711e-02, 3.85326305e-03, 6.28994830e-02, 4.77903370e-02,
        1.47520699e-02, 1.64217090e-02, 3.17811992e-04, 1.67872428e-02,
        4.17044541e-02, 8.23731687e-03],
       [2.65840120e-01, 4.32225643e-02, 7.05551869e-01, 5.36070568e-01,
        1.65475930e-01, 1.84204494e-01, 3.56493940e-03, 1.88304735e-01,
        4.67804410e-01, 9.23990792e-02],
       [1.75526264e-01, 2.85385638e-02, 4.65854754e-01, 3.53951330e-01,
        1.09258797e-01, 1.21624707e-01, 2.35382265e-03, 1.24331973e-01,
        3.08877232e-01, 6.10083428e-02],
       [1.77779762e-01, 2.89049569e-02, 4.71835642e-01, 3.58495543e-01,
        1.10661519e-01, 1.23186189e-01, 2.38404226e-03, 1.25928212e-01,
        3.12842760e-01, 6.17915999e-02],
       [1.85312970e-01, 3.01297703e-02, 4.91829119e-01, 3.73686368e-01,
        1.15350670e-01, 1.28406058e-01, 2.48506323e-03, 1.31264271e-01,
        3.26099102e-01, 6.44099459e-02],
       [2.68813575e-01, 4.37060141e-02, 7.13443555e-01, 5.42066584e-01,
   

In [26]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [27]:

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [28]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11549649  0.30555391]
